# Generated by Django 4.2.15 on 2024-08-16 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='goal',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 21, 19, 0, 609250, tzinfo=datetime.timezone.utc)),
        ),
    ]
