# Generated by Django 4.2.15 on 2024-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
