# Generated by Django 4.2.15 on 2024-08-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='goal',
            field=models.DateTimeField(null=True),
        ),
    ]
